apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-tergum
data:
  tergum.yaml: |
    Meta:
      SchemaVersion: 3
    Telemetry:
      CollectBackupLog: true
    Backups:
      - ID: counter-redis
        Source:
          Redis:
            Host: redis
            Port: 6379
        Targets:
          - ID: lates
            FilePath:
              Path: /backup/tergum-latest/redis-latest.rdb
          - ID: file
            File:
              Dir: /backup/tergum/
              Prefix: redis
              Suffix: rdb
