apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  volumeClaimTemplates:
    - metadata:
        name: redis
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: redis
      initContainers:
        - name: set-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 999:999 /data"]
          volumeMounts:
            - name: redis
              mountPath: /data
      containers:
        - name: redis
          image: redis:8
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
